# @author, Jiacheng Ye, 904973

---

- name: Gather all instances info
  os_server_info:
    server: 'ins*'
  register: instances_info

- name: Set IPs to facts for later couchDB usage
  set_fact:
    instance_ips: "{{ instances_info.openstack_servers | map(attribute='public_v4') | list | sort }}"

- name: Add host
  add_host:
    name: '{{ item }}'
    groups: COMP90024
  loop: '{{ instance_ips }}'

- name: Register master
  add_host:
    name: "{{ instance_ips | first }}"
    groups: Master

- name: Register workers
  add_host: 
    name: '{{ item }}'
    groups: Workers
  loop: '{{ instance_ips[1:] }}'

- name: Register worker 1
  add_host:
    name: '{{ item }}'
    groups: Worker1
  loop: '{{ instance_ips[1:2] }}'

- name: Register worker 2
  add_host:
    name: '{{ item }}'
    groups: Worker2
  loop: '{{ instance_ips[2:] }}'