# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China
# workshop

---

# Remove security group rules
- name: Remove security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: absent
  loop: '{{ security_groups }}'

# Remove a security group
- name: Remove a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: absent
  loop: '{{ security_groups }}'

