# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China


---

- name: Register master node ip from inventory for convinience
  set_fact:
    master: "{{ groups['Master'][0] }}"

- name: Unzip
  # become: yes
  # unarchive:
  #   src: '~/{{ git.repo_name }}/app/backend/upload_data/data.zip'
  #   dest: '~/{{ git.repo_name }}/app/backend/upload_data'
  #   remote_src: yes
  command: 'chdir=/home/ubuntu/{{ git.repo_name }}/app/backend/upload_data unzip data.zip'

- name: Prepare data
  become: yes
  command: 'chdir=/home/ubuntu/{{ git.repo_name }}/app/backend sh run_upload_data.sh'
  when: "ansible_host == master"

- name: Start a container for app
  become: yes
  command: 'chdir=/home/ubuntu/{{ git.repo_name }}/app/ sh run.sh'
  when: "ansible_host == master"