# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China

---

# - name: Create app directory
#   become: yes
#   file:
#     path: 'app'
#     recurse: yes
#     state: directory
#     owner: ubuntu
#     group: ubuntu

# - name: Copy file
#   become: yes
#   command: "scp {{ playbook_dir[:-8] }}/app root@{{ ansible_host }}:~/app"
#   become: yes
# scp -i ~/desktop/ccc/comp90024-assignment2.pem -pr ~/desktop/ccc/comp90024-assignment-2/app ubuntu@172.26.128.169:~/

# - name: Copy file
#   become: yes
#   synchronize:
#     src: '{{ playbook_dir[:-8] }}/app/'
#     dest: ~/app/
#     owner: '0'
#     group: '0'

- name: Remove previous folder
  become: yes
  command: 'rm -rf {{ git.repo_name }}'
  
- name: Clone
  become: no
  command: 'git clone {{ git.repo }}'
