# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China

apt_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg-agent

docker_packages:
  - docker-ce
  - docker-ce-cli 
  - containerd.io

volumes:
  - device: /dev/vdb
    mountpoint: /data

couch:
  name: 'couchdb'
  image: ibmcom/couchdb3
  version: '3.1.1'
  user: 'admin'
  pwd: 'admin'
  cookie: 'comp90024_cookie'
  secret: 'comp90024_secret'
  port: 5984
  dir: /data/couchdb
  volume_path: /data/couchdb/data
  num_nodes: 3
