# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China

---
# https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html
# process are followed by the instructions from the lecture 9-10

# - name: Debug
#   debug:
#     msg: 
#       - "{{ ansible_hostname }} "
#       - "{{ ansible_host }}"
#       - "{{ inventory_hostname }}"

- name: Install dependencies
  become: yes
  apt:
    name: ['xfsprogs']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Make file system
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

- name: Create directory
  become: yes
  file:
    path: "{{ item.mountpoint }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ volumes }}"

- name: Mount device
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"
