# @author, Jiacheng Ye, 904973

-
# https://docs.ansible.com/ansible/latest/collections/community/general/filesystem_module.html
# process are followed by the instructions from the lecture 9-10

- name: Create directory
  become: yes
  file:
    path: "{{ item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

- name: Create a ext4 filesystem on /dev/vdb
  filesystem:
    fstype: ext4
    dev: /dev/
    opts: -cc
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

- name: Checking folders
  tags: 'volumes'
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  with_items:
    - "{{ volumes }}"


- name: Mount device
  tags: 'volumes'
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"
