# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China
# workshop

---

- name: Retrieve Openstacks
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack/post-instances

- name: Deploy
  hosts: COMP90024
  gather_facts: true
  vars_files:
    - vars/config.yaml
  roles:
    # - role: deploy/copy-directory
    # - role: deploy/couchdb
    # - role: deploy/harvester
    - role: deploy/app