# @author, Jiacheng Ye, 904973
# workshop

---

- name: Initiate Openstacks
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - vars/mrc.yaml
  gather_facts: true

  roles:
    # - role: openstack/common
    # - role: openstack/images
    # - role: openstack/volumes
    # - role: openstack/security-groups
    # - role: openstack/instances
    - role: openstack/post-instances
    # - role: openstack-volume-snapshot


# change hosts to COMP90024 to start the tasks

- name: Set Up Dependencies On Each VM
  hosts: COMP90024
  gather_facts: true
  vars_files:
    - vars/config.yaml
  roles:
    # - role: set-up/add-proxy
    # - role: set-up/mount-volumes
    # - role: set-up/install-packages
    - role: set-up/post-docker-installation


- name: Deploy
  hosts: COMP90024
  gather_facts: true
  vars_files:
    - vars/config.yaml
  roles:
    - role: deploy/couchdb