# @author, Jiacheng Ye, 904973
# workshop

---

- name: Initiate Openstacks
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack/remove/remove-instances
    - role: openstack/remove/remove-volumes
    - role: openstack/remove/remove-security-groups
    # - role: openstack-volume-snapshot