# @team 35
# @author Jiacheng Ye   904973      Shanghai, China
# @author Shiyi Xu      780801      Melbourne, Australia
# @author Yuyao Ma      1111182     Yinchuan, China
# @author Yujing Guan   1011792     Fuzhou, China
# @author Zexin Yu      10328021    Dalian, China

---

- name: Initiate Openstacks
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  vars_files:
    - vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack/remove/remove-instances
    - role: openstack/remove/remove-volumes
    - role: openstack/remove/remove-security-groups
    # - role: openstack-volume-snapshot