# @author, Jiacheng Ye, 904973
# workshop

---

- name: Pre_load security_groups
  set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

# Remove an instance on NeCTAR
- name: Remove an instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance.image }}'
    key_name: '{{ instance.key_name }}'
    flavor: '{{ instance.flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: absent
  loop: '{{ instances }}'
  register: os_instance