# @author, Jiacheng Ye, 904973
---

# - name: Start a container with a couchdb node
#   become: yes
#   docker_container:
#     name: "{{ couchdb_container_name}}"
#     image: "{{ couchdb_image }}"
#     ports:
#       - "{{couchdb_port}}:{{couchdb_port}}" # 80 due to change security_group later
#       - "9100:9100"
#       - "4369:4369"
#     env:
#       COUCHDB_PASSWORD: "{{ couchdb_pass }}"
#       COUCHDB_USER: "{{ couchdb_user }}"
#       NODENAME: "{{ ansible_host }}"
#       COUCHDB_SECRET: "{{ couchdb_cookie }}"

- name: Create couch directory
  become: yes
  file:
    path: '{{ couch.dir }}'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Upload compose file by using j2
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: '{{ couch.dir }}/docker-compose.yaml'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create data directory
  become: yes
  file:
    path: '{{ couch.dir }}/data'
    recurse: yes
    state: directory

- name: run docker compose
  docker_compose:
    project_src: '{{ couch.dir }}'
    pull: yes
    state: present
    remove_orphans: yes
    recreate: smart

    # https://github.com/AURIN/comp90024/blob/master/couchdb/macos/run.sh
- name: Wait for a while
  wait_for:
    port: 5984
    timeout: 60