# @author, Jiacheng Ye, 904973

---
# Basic packages
- name: Install utils
  become: yes
  apt:
    name: ['git', 'python3', 'curl', 'wget', 'python3-pip']
    state: latest
    install-recommends: no
    update_cache: yes


# Docker
# the processes are from https://docs.docker.com/engine/install/ubuntu/
# googled to transcript them into ansible playbook style
# helped tutorial: 
#   https://snjksh.wordpress.com/2020/05/11/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-2-04/
#   https://graspingtech.com/install-docker-ansible/
# - name: Uninstall old docker
#   become: yes
#   apt:

- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: Install docker required apt packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes

# https://www.quora.com/Why-do-we-require-a-GPG-key-downloading-Docker-packages
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up stable version for apt repository
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
    state: present

- name: Install Docker
  become: yes
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: latest